name: Playwright 自动化测试

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # 测试多个浏览器
        browser: [chromium, firefox, webkit]
        # 测试多个环境
        environment: [local, staging]

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: 安装依赖
        run: pnpm install --frozen-lockfile

      - name: 安装 Playwright 浏览器
        run: npx playwright install --with-deps ${{ matrix.browser }}

      - name: 构建项目
        run: pnpm run build

      - name: 类型检查
        run: pnpm run type-check

      - name: 代码检查 (非阻塞)
        run: pnpm run lint || true
        continue-on-error: true

      - name: 启动测试服务器
        run: |
          # 根据环境配置不同的启动方式
          if [ "${{ matrix.environment }}" = "local" ]; then
            pnpm run dev &
            echo "LOCAL_SERVER_PID=$!" >> $GITHUB_ENV
          else
            echo "使用远程测试环境: ${{ matrix.environment }}"
          fi
        env:
          NODE_ENV: test

      - name: 等待服务启动
        if: matrix.environment == 'local'
        run: |
          npx wait-on http://localhost:3000 --timeout 120000
          npx wait-on http://localhost:8787 --timeout 120000

      - name: 运行 Playwright 测试
        run: npx playwright test --project=${{ matrix.browser }}
        env:
          TEST_ENV: ${{ matrix.environment }}
          TEST_BASE_URL: ${{ matrix.environment == 'local' && 'http://localhost:3000' || format('https://{0}.colorsofthewind.club', matrix.environment) }}
          API_BASE_URL: ${{ matrix.environment == 'local' && 'http://localhost:8787' || format('https://api-{0}.colorsofthewind.club', matrix.environment) }}
          TEST_SESSION_ID: ${{ github.run_id }}-${{ matrix.browser }}-${{ matrix.environment }}

      - name: 停止本地服务器
        if: matrix.environment == 'local' && env.LOCAL_SERVER_PID
        run: kill $LOCAL_SERVER_PID || true

      - name: 上传测试报告
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.browser }}-${{ matrix.environment }}
          path: test-results/
          retention-days: 30

      - name: 上传截图
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots-${{ matrix.browser }}-${{ matrix.environment }}
          path: test-results/screenshots/
          retention-days: 7

  # 性能和负载测试作业
  performance-test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: 安装依赖
        run: pnpm install --frozen-lockfile

      - name: 安装 Playwright 浏览器
        run: npx playwright install --with-deps chromium

      - name: 运行性能测试
        run: npx playwright test --project=chromium tests/performance/
        env:
          TEST_ENV: staging
          TEST_BASE_URL: https://staging.colorsofthewind.club
          API_BASE_URL: https://api-staging.colorsofthewind.club

      - name: 生成性能报告
        run: |
          echo "## 🚀 性能测试结果" >> $GITHUB_STEP_SUMMARY
          echo "测试环境: staging" >> $GITHUB_STEP_SUMMARY
          echo "浏览器: Chromium" >> $GITHUB_STEP_SUMMARY

          if [ -f "test-results/performance-metrics.json" ]; then
            echo "### 关键指标" >> $GITHUB_STEP_SUMMARY
            cat test-results/performance-metrics.json >> $GITHUB_STEP_SUMMARY
          fi

  # 测试结果汇总
  test-summary:
    runs-on: ubuntu-latest
    needs: [test, performance-test]
    if: always()

    steps:
      - name: 下载所有测试报告
        uses: actions/download-artifact@v4
        with:
          pattern: playwright-report-*
          path: all-reports/

      - name: 生成测试摘要
        run: |
          echo "## 🧪 测试执行摘要" >> $GITHUB_STEP_SUMMARY
          echo "### 环境矩阵测试结果" >> $GITHUB_STEP_SUMMARY

          total_tests=0
          passed_tests=0
          failed_tests=0

          for report_dir in all-reports/*/; do
            if [ -f "$report_dir/test-results.json" ]; then
              # 解析测试结果 (简化版本)
              echo "- $(basename $report_dir): ✅ 测试完成" >> $GITHUB_STEP_SUMMARY
            else
              echo "- $(basename $report_dir): ❌ 测试失败或未完成" >> $GITHUB_STEP_SUMMARY
            fi
          done

          echo "### 迭代验收状态" >> $GITHUB_STEP_SUMMARY
          echo "- 迭代 1: 基础架构测试 - ${{ needs.test.result == 'success' && '✅ 通过' || '❌ 失败' }}" >> $GITHUB_STEP_SUMMARY

      - name: 发送通知 (可选)
        if: failure()
        run: |
          echo "测试失败，需要检查以下内容："
          echo "1. 检查测试日志和截图"
          echo "2. 验证测试环境状态"
          echo "3. 检查代码变更影响"

# 环境变量配置
env:
  # 防止 Playwright 收集遥测数据
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: false
  # 设置测试并发度
  PLAYWRIGHT_WORKERS: 1
  # CI 环境标识
  CI: true
